# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25588c1b01b9f065cc542a1b888c812f8a0ef6566de57ade9d8baae9c3d70c8986f635ef7d8604fa15d09b8d91d09f59a2ca5038ac66e8e9a065275d7d55edc5

test:
  secret_key_base: d05f51f88edb144a6be0cdf9882862216e10a8d31fdb42fcfde16c27af92c86da539569aac2fb4b59e7743b706f829d338e756afcc0826de480e4f0a26aaee41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
